environment:
  matrix:
    - CONDA_INSTALL_LOCN: "C:\\Miniconda-x64"
      CONDA_PY: "27"

    - CONDA_INSTALL_LOCN: "C:\\Miniconda3-x64"
      CONDA_PY: "37"

install:
  - set CPU_COUNT=2
  - set PYTHONUNBUFFERED=1
  - call "%CONDA_INSTALL_LOCN%\Scripts\activate.bat"
  # update conda
  - conda update --yes --quiet conda
  # add channels
  - conda config --add channels conda-forge
  - conda config --set auto_update_conda false
  # install conda-build
  - conda install --yes --quiet conda-build
  # needed for building extensions in python 2.7 x64 with cmake
  - conda install --yes --quiet vs2008_express_vc_python_patch
  - call setup_x64
  # info for debugging
  - conda info

build_script:
  - conda build --no-test --quiet recipes\conda || exit 1
  - set PKGPATH="%CONDA_INSTALL_LOCN%\conda-bld\win-64\*.tar.bz2"
  - dir /b "%PKGPATH%" || exit 1

test_script:
  - conda build --test "%PKGPATH%" || exit 1
