- name: Ryan Volz
  email: rvolz@mit.edu
  alternate_emails:
  - ryan.volz@gmail.com
  - rvolz@haystack.mit.edu
  github: ryanvolz
  num_commits: 663
  first_commit: 2017-04-07 17:54:29
- name: Frank Lind
  email: flind@mit.edu
  github: fdlind
  aliases:
  - flind
  alternate_emails:
  - flind@haystack.mit.edu
  - flind@orion.haystack.mit.edu
  num_commits: 4
  first_commit: 2017-05-26 09:24:02
- name: John Swoboda
  email: swoboj@mit.edu
  github: jswoboda
  num_commits: 61
  first_commit: 2017-04-12 15:28:37
- name: Juha Vierinen
  email: jvi019@uit.no
  alternate_emails:
  - jvierine@gmail.com
  github: jvierine
  num_commits: 1
  first_commit: &id001 2019-11-08 16:10:04.463013
- name: Bill Rideout
  email: brideout@mit.edu
  alternate_emails:
  - brideout@haystack.mit.edu
  num_commits: 0
  first_commit: *id001
- name: dependabot[bot]
  email: 49699333+dependabot[bot]@users.noreply.github.com
  num_commits: 7
  first_commit: 2025-01-15 23:43:21
  is_org: true
- name: Daniel Sheen
  email: dsheen@mit.edu
  num_commits: 8
  first_commit: 2025-07-14 15:01:42
