# This file defines the configuration for building conda packages with CI.
# The actual files for running the CI are created/updated by "conda-smithy".
# You should edit only this file and the recipe files (in recipe_dir, below)
# and not any of the automatically-generated files in e.g. .ci_support,
# .scripts, or .github/workflows/conda-build.yml.

# To update the generated conda CI files after a change here or in the recipe,
# or because of updates to conda-smithy, run
#
#   conda-smithy rerender -c auto
#
# which will automatically commit any changes.
# ***** RUN THE ABOVE TO CHECK FOR UPDATES WHENEVER EDITS ARE MADE HERE *****

# The CI will build conda packages for commits and pull requests, and it will
# upload the packages to Anaconda Cloud on commits to the branch specified
# in the configuration below. The channel and label that the packages are
# uploaded to are set in the recipe directory in conda_build_config.yaml.
# Uploads to Anaconda Cloud also require an API token to be set to the
# BINSTAR_TOKEN environment variable. Documentation for token generation:
# https://docs.anaconda.com/anacondaorg/user-guide/tasks/work-with-accounts/#creating-access-tokens
# To populate BINSTAR_TOKEN for CI jobs, add the token as a secret, e.g.:
# https://docs.github.com/en/actions/reference/encrypted-secrets

# See https://conda-forge.org/docs/maintainer/conda_forge_yml.html for
# documentation on possible keys and values.

build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
clone_depth: 0
github_actions:
  store_build_artifacts: true
provider:
  linux: github_actions
  osx: github_actions
  win: github_actions
recipe_dir: recipes/conda
# skip unnecessary files since this is not a full-fledged conda-forge feedstock
skip_render:
  - README.md
  - LICENSE.txt
  - .gitattributes
  - .gitignore
  - build-locally.py
  - LICENSE
  - .github/CONTRIBUTING.md
  - .github/ISSUE_TEMPLATE.md
  - .github/PULL_REQUEST_TEMPLATE.md
  - .github/workflows
test: native_and_emulated
# enable uploads to Anaconda Cloud from specified branches only
# ***** UPDATE THIS FOR MAINTENANCE BRANCHES ********************************
upload_on_branch: master
