cross_compiler_target_platform:  # [win]
  - win-64                     # [win]
c_compiler:                    # [win]
  - vs2008                     # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
cxx_compiler:                  # [win]
  - vs2008                     # [win]
  - vs2015                     # [win]
  - vs2015                     # [win]
macos_min_version:             # [osx]
  - 10.9                       # [osx]
macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.9                       # [osx]
target_platform:
  - win-64                     # [win]
zip_keys:
  - python
  - vc                         # [win]
  - c_compiler                 # [win]
  - cxx_compiler               # [win]

# TODO: remove these when run_exports are added to the packages.
pin_run_as_build:
  hdf5:
    max_pin: x.x.x

# Pinning packages
hdf5:
  - 1.10.1
numpy:
  - 1.9   # [unix]
  - 1.11  # [win]
python:
  - 2.7
  - 3.5
  - 3.6
vc:     # [win]
  - 9   # [win]
  - 14  # [win]
  - 14  # [win]

