name: conda-matrix

on: [push, pull_request]

jobs:
  conda-build:
    name: ${{ matrix.os }} (python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.6', '3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - name: Set up conda environment
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: dev-env
          environment-file: recipes/conda/dev-env.yml
          condarc-file: recipes/conda/.condarc
          conda-build-version: '*'
          auto-update-conda: true
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Build and Test
        shell: bash -l {0}
        run: |
          conda build -m $CONDA_PREFIX/conda_build_config.yaml --variants "{python: [${{ matrix.python-version }}]}" recipes/conda
