name: conda-matrix

on: [push, pull_request]

jobs:
  conda-build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dev-env
          environment-file: recipes/conda/dev-env.yml
          condarc-file: recipes/conda/.condarc
          conda-build-version: '*'
          auto-update-conda: true
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Build and Test
        shell: bash -l {0}
        run: |
          conda build -m $CONDA_PREFIX/conda_build_config.yaml recipes/conda
